### ISSUE TITLE
Licensing code

### ISSUE THREAD

**Issue by vladfaust** [ysbaddaden/http2#10]
Hey Julien,

Thanks for your work on this shard. HTTP/2 is a very cool feature indeed, but the lack of license legally stops potential contributions and prohibits re-using your code. Would you mind adding a license to the project?

**Comment by ysbaddaden** [comment]
Sure, can you open a PR that adds the [Apache-2.0](https://opensource.org/licenses/Apache-2.0) license (same as Crystal itself).

**Comment by vladfaust** [comment]
Yas, will do
