### ISSUE TITLE
Project state

### ISSUE THREAD

**Issue by spalladino** [ysbaddaden/http2#4]
Hey @ysbaddaden! I was wondering about the current state of this project. I see there are two issues still open on flow control. Is there all that's missing from completing the spec? Do you have plans on working on this again, or would be willing to accept contributions if not? Thanks a lot!!

**Comment by ysbaddaden** [comment]
Obviously, I somewhat lost interest. HTTP2 is far too huge and tuned for very large websites. It's really hard (with quirks) and even harder to have an implementation that ain't buggy :sob:

That being said, I'd love my code to be reviewed, for starters.

Then integrate the circular buffer —that might fit nicely into Crystal stdlib as IO:: CircularBuffer— so we could implement support for incoming control flow. That is, fill a 64KB buffer (for example), when buffer gets near 16KB, increase stream window size, so the client can send more data, etc.

Then check the issue tracker of other implementations for obvious bugs, and be (almost) sure to find them in mine!

**Comment by ysbaddaden** [comment]
It looks like I never pushed my CircularBuffer! I'll do that in some hours.

**Comment by spalladino** [comment]
Thanks @ysbaddaden. This looks like a good opportunity for folks (with good programming experience, for sure) that would like to contribute to the language, yet are unsure on where to start.
